### ISSUE TITLE
你好，大牛，请教个问题

### ISSUE THREAD

**Issue by YangXiaojun-1024** [siqin/SimpleCalendar#1]
大牛，请教个问题，我下载了你的源码，因为项目中要用到一个类型日历的功能，但我遇到一问题，就是你的日历在上下连续切换的时候，会出现卡在一半的情况，我尝试着解决，但没能解决，希望您能给点帮助😃

**Comment by siqin** [comment]
很抱歉这么晚才看到，那个是一两年前的代码了，我现在也记不清了 😓
